name: Ubuntu 18.04 CI (GCC 7, 6, 5)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {cxx: -DCMAKE_CXX_COMPILER=g++-5}
          - {cxx: -DCMAKE_CXX_COMPILER=g++-6}
          - {cxx: } # default compiler 7
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.0
        with:
          cmake-version: '3.9.x'
      - name: Install older compilers
        run: |
          sudo -E apt-get update
          sudo -E apt-get install -y --force-yes g++-5 g++-6
      - name: Prepare build dir
        run: mkdir build
      - name: Configure
        run: cd build && cmake ${{matrix.cxx}} -DFASTFLOAT_TEST=ON ..
      - name: Build
        run: cmake --build build
      - name: Run basic tests
        run: cd build && ctest --output-on-failure -R basictest
