name: VS16-CLANG-CI

on: [push, pull_request]

jobs:
  ci:
    name: windows-vs16
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - vs: VS16Win64
          - vs: VS16Win32
    steps:
    - uses: actions/checkout@v2
    - name: 'Run CMake with VS16'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: "${{ github.workspace }}/../../_temp/windows"
        cmakeBuildType: Release   
        buildWithCMake: true
        cmakeGenerator: ${{matrix.vs}}
        cmakeAppendedArgs:  -T ClangCL -DFASTFLOAT_TEST=ON
        buildWithCMakeArgs: --config Release  
        
    - name: 'Run CTest'
      run: ctest -C Release -R basictest  --output-on-failure 
      working-directory: "${{ github.workspace }}/../../_temp/windows"
